#!/bin/bash -ex

apt update
apt install -y git python3 clang-tools python3-pip
git clone https://github.com/PatrikAAberg/dmce.git
pip3 install numpy
cd dmce
./build-deb
dpkg -i dmce-*.deb
cd ..
git clone https://github.com/PatrikAAberg/dmce-examples.git
export USER="root" # not set in docker container
dmce-setup
cd dmce-examples
dmce-set-profile coverage -i patchcov
pushd patchcov
git apply 000-patchcov.patch
popd
dmce-launcher -n 1
git diff
rm -f /tmp/${USER}/dmce/dmcebuffer.bin
cd patchcov
./build && ./test-patchcov
dmce-summary-bin -v /tmp/${USER}/dmce/dmcebuffer.bin /tmp/${USER}/dmce/dmce-examples/probe-references.log
