#!/bin/bash -ex

apt update
apt install -y fakeroot git python3 perl clang-tools
git clone https://github.com/PatrikAAberg/dmce.git
cd dmce
./build-deb
dpkg -i dmce-1.1-0.deb
cd ..
git clone https://github.com/tmux/tmux.git
dmce-configure-global
cd tmux
dmce-launcher -n 10000
bash

