#!/bin/bash -ex

apt update
apt install -y git python3 clang-tools python3-pip
pip3 install numpy colorama
git clone https://github.com/PatrikAAberg/dmce.git
cd dmce
./build-deb
dpkg -i dmce-*.deb
cd ..
git clone https://github.com/PatrikAAberg/dmce-examples.git
export USER="root" # not set in docker container
dmce-setup
cd dmce-examples
dmce-set-profile trace -i simplecrash
dmce -n 10000
pushd simplecrash
./build
set +e
rm -f /tmp/${USER}/dmce/dmcebuffer.bin
rm -rf /tmp/${USER}/dmce-trace-buffer-lock
./simplecrash
set -e
popd
dmce-trace --numvars 5 --sourcewidth 80 -A 3 -B 2 -t --hl /tmp/${USER}/dmce/dmcebuffer.bin /tmp/${USER}/dmce/dmce-examples/probe-references.log $(pwd)
bash
