#!/bin/bash -ex

apt update
apt install -y build-essential pkg-config libtool libevent-dev libncurses5-dev libncursesw5-dev fakeroot git python3 clang-tools python3-pip automake bison make autoconf
pip3 install numpy colorama
git clone https://github.com/PatrikAAberg/dmce.git
cd dmce
./build-deb
dpkg -i dmce-1.2-0.deb
cd ..
git clone https://github.com/tmux/tmux.git
export USER="root" # not set in docker container
dmce-setup
cd tmux
git checkout 2.9
dmce -n 10000
./autogen.sh
./configure
make -j
bash

