#!/bin/bash -ex

apt update
apt install -y git build-essential pkg-config automake make python3 clang-tools liblzma-dev libpcre3-dev python3-pip python3-cram zlib1g-dev
git clone https://github.com/PatrikAAberg/dmce.git
pip3 install cram
ln -s /usr/bin/cram3 /usr/bin/cram
cd dmce
./build-deb
dpkg -i dmce-1.1-0.deb
cd ..
git clone https://github.com/ggreer/the_silver_searcher.git
export USER="root" # not set in docker container
dmce-configure-global
cd the_silver_searcher
dmce-launcher -n 10000
./autogen.sh
./configure
make -j
make test
bash

