#!/bin/bash -ex

apt update
apt install -y git python3 clang-tools python3-pip
git clone https://github.com/PatrikAAberg/dmce.git
cd dmce
./build-deb
dpkg -i dmce-*.deb
cd ..
git clone https://github.com/PatrikAAberg/dmce-examples.git
export USER="root" # not set in docker container
dmce-setup
cd dmce-examples
./config-simple
dmce-launcher -n 10000
git diff
cd simple
./build
./simple
bash
