#!/bin/bash -ex

apt update
apt install -y git python3 clang-tools python3-pip
pip3 install numpy colorama
git clone https://github.com/PatrikAAberg/dmce.git
cd dmce
./build-deb
dpkg -i dmce-1.2-0.deb
cd ..
git clone https://github.com/PatrikAAberg/dmce-examples.git
export USER="root" # not set in docker container
dmce-configure-global
cd dmce-examples
./config-simple
dmce-launcher -n 10000
git diff
cd simple
./build
./simple
bash
