#!/bin/bash -ex

apt update
apt install -y git build-essential pkg-config automake make python3 clang-tools liblzma-dev libpcre3-dev python3-pip python3-cram zlib1g-dev
git clone https://github.com/PatrikAAberg/dmce.git
pip3 install cram
ln -s /usr/bin/cram3 /usr/bin/cram
cd dmce
./build-deb
dpkg -i dmce-1.2-0.deb
cd ..
git clone https://github.com/ggreer/the_silver_searcher.git
export USER="root" # not set in docker container
dmce-setup
sed -i "s|DMCE_PROBE_SOURCE:.*|DMCE_PROBE_SOURCE:/usr/share/dmce/dmce-probe-trace-atexit-D5-CB.c|" /root/.dmceconfig
sed -i "s|DMCE_PROBE_PROLOG:.*|DMCE_PROBE_PROLOG:/usr/share/dmce/dmce-prolog-trace-D5.c|" /root/.dmceconfig
sed -i "s|DMCE_NUM_DATA_VARS:.*|DMCE_NUM_DATA_VARS:5|" /root/.dmceconfig
cd the_silver_searcher
dmce -n 10000
./autogen.sh
./configure
make -j
make test
bash
