#!/bin/bash -e


version=$(grep Version debian/control | cut -d' ' -f2)
gitdir=$(pwd)

echo "Building deb package version $version"
exit

# Tree structure
rm -rf /tmp/$USER/dmce/debian-build
mkdir -p /tmp/$USER/dmce/debian-build

pushd /tmp/$USER/dmce/debian-build
mkdir -p dmce-$version/DEBIAN
mkdir -p dmce-$version/usr
mkdir -p dmce-$version/usr/bin
mkdir -p dmce-$version/usr/share/dmce

# deb files
cp $gitdir/debian/* dmce-$version/DEBIAN

# Program files
cp $gitdir/dmce-launcher dmce-$version/usr/bin/
cp $gitdir/dmce-configure-local dmce-$version/usr/bin/
cp $gitdir/dmce-configure-global dmce-$version/usr/bin/
cp $gitdir/dmce-summary dmce-$version/usr/bin/
cp $gitdir/dmce-probe*   dmce-$version/usr/share/dmce/
cp $gitdir/cmdlookuphook.sh dmce-$version/usr/share/dmce/
cp $gitdir/create-clang-diff dmce-$version/usr/share/dmce/
cp $gitdir/dmce-remove-relpaths.sh dmce-$version/usr/share/dmce/
cp $gitdir/dmce.sh dmce-$version/usr/share/dmce/
cp $gitdir/generate-compile-commands.py dmce-$version/usr/share/dmce/
cp $gitdir/generate-probefile.py dmce-$version/usr/share/dmce/


cp $gitdir/constructs.exclude dmce-$version/usr/share/dmce/
cp $gitdir/dmce.exclude dmce-$version/usr/share/dmce/
cp $gitdir/dmce.include dmce-$version/usr/share/dmce/
cp $gitdir/recognizedexpressions.py dmce-$version/usr/share/dmce/

fakeroot dpkg-deb --build dmce-${version}
popd
exit 0
