#!/usr/bin/env bash

set -e

if [ ! -s "debian/control" ]; then
	echo "error: cd to DMCE base dir"
	exit 1
elif ! command -v fakeroot > /dev/null; then
	echo "error: command 'fakeroot' missing"
	exit 1
fi

version=$(grep ^Version debian/control | cut -d' ' -f2)
gitdir=$PWD

function cleanup {
	rm -rf "${d:?}"
}
trap cleanup EXIT

# tree structure
d=$(mktemp -d)
cd "${d}" || exit
mkdir -p dmce-"${version}"/DEBIAN
mkdir -p dmce-"${version}"/usr
mkdir -p dmce-"${version}"/usr/bin
mkdir -p dmce-"${version}"/usr/share/dmce

# deb files
cp -a "${gitdir}"/debian/* dmce-"${version}"/DEBIAN

# Program files
cp -a "${gitdir}"/bin/dmce dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/bin/dmce-launcher dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/bin/dmce-trace dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/bin/dmce-diff dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/bin/dmce-trace-viewer dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/bin/dmce-trace-tgui dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/bin/dmce-configure-local dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/bin/dmce-setup dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/bin/dmce-set-profile dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/bin/dmce-summary* dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/bin/dmce-stats dmce-"${version}"/usr/bin/
cp -a "${gitdir}"/probe-examples/dmce-probe*   dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/probe-examples/dmce-prolog*   dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/dmce-post-hook*   dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/share/cmdlookuphook.sh dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/share/dmce-copy-headers dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/share/dmce-remove-relpaths.sh dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/share/dmce.sh dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/share/generate-compile-commands.py dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/share/generate-probefile.py dmce-"${version}"/usr/share/dmce/

cp -a "${gitdir}"/constructs.exclude dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/dmce.exclude dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/dmce.include dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/dmce.pos.exclude dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/dmce.pos.include dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/dmce.var.exclude dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/dmce.var.include dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/recognizedexpressions.py dmce-"${version}"/usr/share/dmce/
cp -a "${gitdir}"/dmce-completion.bash dmce-"${version}"/usr/share/dmce/

echo "${version}" > dmce-"${version}"/usr/share/dmce/version

fakeroot dpkg-deb --build dmce-"${version}"
cp -a dmce-"${version}".deb "${gitdir}"/
