#!/usr/bin/env bash

# Copyright (c) 2016 Ericsson AB
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# $1 = <some-path>/<file>.cc.clang.filtereddiff

CLANG_FILE=${1%/*}/${1##*/}
CLANG_FILE=${CLANG_FILE/.filtereddiff}
CLANG_FILE_FILTERED=$1

# @@ -76356,7 +76366 @@ IntegerLiteralHexnumber  'int' 0

function cleanup {
	[ -e "${sed_exp}" ] && rm "${sed_exp}"
}
sed_exp=$(mktemp)
trap cleanup EXIT

# rows starting with "@@"
while read -r line ; do
	arrIN=(${line//+/ })
	ADD=${arrIN[2]}

	# Multi or single line?
	if [[ "$ADD" =~ "," ]]; then
		# Multi line add. Example: "126903,8"
		arrOUT=(${ADD//,/ })
		START_POS=${arrOUT[0]}
		NUM_LINES=${arrOUT[1]}
	else
		# Single line change. Example: "127505"
		START_POS=$ADD
		NUM_LINES=1
	fi

	echo "$START_POS","$(($START_POS+$NUM_LINES-1))""{s/\(.*\)/+\1/};" >> "${sed_exp}"
done <<< "$(grep -n "^@@.*@@" $1)"

# Sanity check
[ "$ADD" == "" ] && exit

sed -f ${sed_exp} $CLANG_FILE > "$CLANG_FILE""diff"
