#!/bin/bash

# Copyright (c) 2016 Ericsson AB
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

git_root=${PWD##*/}

#TODO: extract config and use from both launcher and summary
echo "DMCE summary. Using config file: $HOME/.dmceconfig"

while read dmceconfig; do
  validconfig=$(echo $dmceconfig | egrep -v \#)
  if [ "$validconfig" != ""  ]; then
    conf_var=$(echo $validconfig | cut -d: -f1)
    conf_val=$(echo $validconfig | cut -d: -f2 | envsubst)
    eval $conf_var=\'$conf_val\'
    export $conf_var
  fi
done < $HOME/.dmceconfig

echo "DMCE probe ref log: $DMCE_WORK_PATH/$git_root/probe-references.log "
echo "Test result log   : $1"
echo "$DMCE_EXEC_PATH/print_summary.py $1 $DMCE_WORK_PATH/$git_root/probe-references.log"
$DMCE_EXEC_PATH/print_summary.py $1 $DMCE_WORK_PATH/$git_root/probe-references.log
