#!/bin/bash -e

# Copyright (c) 2016 Ericsson AB
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

cfgpath=$1
installpath=$(which dmce-setup | sed -e 's/\/bin\/dmce-setup//')

if [ "$cfgpath" == "--help" ]; then
    echo "Usage: dmce-setup [--help | Path ]"
    echo "Default configuration path (where to setup dmce configuration) is $cfgpath, but can be specified with an optional argument"
    exit
fi

if [ "$cfgpath" == "" ]; then
    cfgpath=$HOME
fi

echo "DMCE setup"
echo "------------------------"
echo "Creating .dmceconfig file in $cfgpath"

# Remove old config
[ -e $cfgpath/.dmceconfig ] && rm $cfgpath/.dmceconfig
[ -e $cfgpath/.config/dmce ] && rm -r $cfgpath/.config/dmce
mkdir -p $cfgpath/.config/dmce

# Create config file in home directory
cat > $cfgpath/.dmceconfig <<- NoWord
# DMCE install path
DMCE_EXEC_PATH:$installpath/share/dmce

# Working directory root
DMCE_WORK_PATH:/tmp/$LOGNAME/dmce

# config files path. (dmce.exclude, dmce.include etc.)
DMCE_CONFIG_PATH:$cfgpath/.config/dmce

# Command line lookup hook (builds list of individual compile commands per file if not enough with the default ones)
DMCE_CMD_LOOKUP_HOOK:$cfgpath/.config/dmce/cmdlookuphook.sh

# Default compiler command line for c files
DMCE_DEFAULT_C_COMMAND_LINE:gcc -I/usr/include -I/usr/include/sys -isystem /tmp/$LOGNAME/dmce/inc -I/tmp/$LOGNAME/dmce/inc

# Default compiler command line for cpp files
DMCE_DEFAULT_CPP_COMMAND_LINE:gcc -std=c++11 -I/usr/include -I/usr/include/sys -isystem /tmp/$LOGNAME/dmce/inc -I/tmp/$LOGNAME/dmce/inc

# Default compiler command line for h files
DMCE_DEFAULT_H_COMMAND_LINE:gcc -std=c++11 -I/usr/include -I/usr/include/sys -isystem /tmp/$LOGNAME/dmce/inc -I/tmp/$LOGNAME/dmce/inc

# Number of data variables to probe
DMCE_NUM_DATA_VARS:0

# Probe definition c file
DMCE_PROBE_SOURCE:$installpath/share/dmce/dmce-probe-user.c

# Prolog definition c file
DMCE_PROBE_PROLOG:$installpath/share/dmce/dmce-prolog-default.c

# Use system inlcude files (YES | NO)
DMCE_SYS_INCLUDES:NO

# Log files
DMCE_LOG_FILES:/tmp/$LOGNAME/dmce

# git diff algorithm
DMCE_GIT_DIFF_ALGORITHM:histogram

# Some probes need a path for binary output files
DMCE_PROBE_DEFINE:DMCE_PROBE_OUTPUT_FILE_BIN "/tmp/$LOGNAME/dmce/dmcebuffer.bin"

# Some probes need a system wide lock dir
DMCE_PROBE_DEFINE:DMCE_PROBE_LOCK_DIR "/tmp/$LOGNAME/dmce-trace-buffer-lock"
NoWord

echo "Creating dmce config directory as $cfgpath/.config/dmce"
echo "Fetching default config from $installpath/share/dmce"
cp $installpath/share/dmce/constructs.exclude /$cfgpath/.config/dmce/
cp $installpath/share/dmce/dmce.exclude /$cfgpath/.config/dmce/
cp $installpath/share/dmce/dmce.include  /$cfgpath/.config/dmce/
cp $installpath/share/dmce/recognizedexpressions.py /$cfgpath/.config/dmce/
cp $installpath/share/dmce/cmdlookuphook.sh /$cfgpath/.config/dmce/

echo "...done. Please notice that a .dmceconfig file in the git where dmce is launched will override this file."
