#!/bin/bash -e

# Copyright (c) 2016 Ericsson AB
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

echo "Creating .dmceconfig file in $HOME"
echo "Creating dmce config directory as $HOME/.config/dmce"
echo

# Remove old config
[ -e $HOME/.dmceconfig ] && rm $HOME/.dmceconfig
[ -e $HOME/.config/dmce ] && rm $HOME/.config/dmce
mkdir -p $HOMR/.config/dmce

# Create config file in home directory
cat > $HOME/.dmceconfig <<- NoWord
# DMCE install path
DMCE_EXEC_PATH:/usr/share/dmce

# Working directory root
DMCE_WORK_PATH:/tmp/$USER/dmce

# config files path. (dmce.exclude, dmce.include etc.)
DMCE_CONFIG_PATH:$HOME/.config/dmce

# Command line lookup hook (builds list of individual compile commands per file if not enough with the default ones)
DMCE_CMD_LOOKUP_HOOK:$HOME/.config/dmce/cmdlookuphook.sh

# Default compiler command line for c files
DMCE_DEFAULT_C_COMMAND_LINE:gcc -I/usr/include -isystem /tmp/$USER/dmce/inc -I/tmp/$USER/dmce/inc

# Default compiler command line for cpp files
DMCE_DEFAULT_CPP_COMMAND_LINE:gcc -std=c++11 -I/usr/include -isystem /tmp/$USER/dmce/inc -I/tmp/$USER/dmce/inc

# Default compiler command line for h files
DMCE_DEFAULT_H_COMMAND_LINE:gcc -std=c++11 -I/usr/include -isystem /tmp/$USER/dmce/inc -I/tmp/$USER/dmce/inc

# Number of data variables to probe
DMCE_NUM_DATA_VARS:0

# Probe definition c file
DMCE_PROBE_SOURCE:/usr/share/dmce/dmce-probe-user.c

# Probe definition c file
DMCE_PROBE_PROLOG:/usr/share/dmce/dmce-prolog-default.c

# Log files
DMCE_LOG_FILES:/tmp/$USER/dmce
NoWord
echo "...done. Please notice that a .dmceconfig file in the git where dmce is launched will override this file."
