exppatternlist = ['.*-CallExpr\sHexnumber\s<.*\,.*>.*',
                  '.*-CXXMemberCallExpr\sHexnumber\s<.*\,.*>.*',
                  '.*-StaticAssertDecl\sHexnumber\s<.*\,.*>.*',
                  '.*-ConditionalOperator\sHexnumber\s<.*\,.*>.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'\*\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'\/\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'\-\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'\+\'.*',
                  '.*UnaryOperator Hexnumber <.*\,.*>.*\'\+\+\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'\&\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'\|\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'=\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'<\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'>\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'==\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'!=\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'\&\&\'.*',
                  '.*BinaryOperator Hexnumber <.*\,.*>.*\'\|\|\'.*',
                  '.*CompoundAssignOperator Hexnumber <.*\,.*>.*\'\+\=\'.*',
                  '.*CompoundAssignOperator Hexnumber <.*\,.*>.*\'\-\=\'.*',
                  '.*ReturnStmt Hexnumber <.*\,.*>.*']
