#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2022 Ericsson AB
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

if [ ! -f "$DMCE_PROBE_REFERENCES" ]; then
	exit 0
fi
echo "DMCE Post hook: $0 $DMCE_PROBE_REFERENCES"

# read filecontent into variable
content=$(cat "$DMCE_PROBE_REFERENCES")

# use awk to retrive filename column, then sort the names
files=$(awk -F':' '{print $2}' <<< "${content}"|sort|uniq)

for f in $files; do
	SED_CMD=""
	# grep on specific filename and retrieve all line numbers
	lines=$(grep ":${f}:" <<< "${content}" | awk -F':' '{print $3}')
	for l in $lines; do
		SED_CMD+=" -e ${l}s/DMCE_PROBE\([0-9]*\)(\([0-9]\+\)/DMCE_PROBE\1(\2,$RANDOM/"
	done
	echo "$f"
	# shellcheck disable=SC2086
	sed -i $SED_CMD "$f" &
done
wait
